# Generated by Django 3.0.5 on 2020-04-26 23:53

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Armor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('L', 'Light'), ('M', 'Medium'), ('H', 'Heavy'), ('S', 'Shield')], max_length=10)),
                ('cost', models.CharField(default='-', max_length=10)),
                ('ac_bonus', models.IntegerField(default=1, verbose_name='AC Bonus')),
            ],
            options={
                'verbose_name_plural': 'Armor',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(default=uuid.uuid4)),
                ('level', models.IntegerField(default=1)),
                ('hit_points', models.IntegerField(default=1)),
                ('hit_points_max', models.IntegerField(default=1, verbose_name='Max HP')),
                ('xp', models.IntegerField(default=0, verbose_name='XP')),
                ('str', models.IntegerField(default=10, verbose_name='STR')),
                ('dex', models.IntegerField(default=10, verbose_name='DEX')),
                ('mind', models.IntegerField(default=10, verbose_name='MIND')),
                ('armor_class', models.IntegerField(default=10)),
                ('copper', models.IntegerField(default=0)),
                ('silver', models.IntegerField(default=0)),
                ('gold', models.IntegerField(default=0)),
                ('platinum', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('armor', models.ManyToManyField(blank=True, to='characters.Armor')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('abilities', models.TextField(blank=True)),
                ('phys_bonus', models.IntegerField(default=0)),
                ('sub_bonus', models.IntegerField(default=0)),
                ('know_bonus', models.IntegerField(default=0)),
                ('com_bonus', models.IntegerField(default=0)),
                ('light_armor', models.BooleanField(default=False)),
                ('medium_armor', models.BooleanField(default=False)),
                ('heavy_armor', models.BooleanField(default=False)),
                ('shields', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Classes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Clothing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('cost', models.CharField(default='-', max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Clothing',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Gear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('cost', models.CharField(default='-', max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Gear',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('abilities', models.TextField(blank=True)),
                ('skill_roll_bonus', models.IntegerField(default=0, verbose_name='Skill Roll Bonus')),
                ('str_bonus', models.IntegerField(default=0, verbose_name='STR Bonus')),
                ('dex_bonus', models.IntegerField(default=0, verbose_name='DEX Bonus')),
                ('mind_bonus', models.IntegerField(default=0, verbose_name='MIND Bonus')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('L', 'Light'), ('1H', 'One-Handed'), ('2H', 'Two-Handed'), ('R', 'Ranged')], max_length=10)),
                ('cost', models.CharField(default='-', max_length=10)),
                ('damage', models.CharField(default='-', max_length=10)),
                ('range', models.CharField(default='-', max_length=10)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CharacterGear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characters.Character')),
                ('gear', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characters.Gear')),
            ],
        ),
        migrations.AddField(
            model_name='character',
            name='character_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='characters.Class'),
        ),
        migrations.AddField(
            model_name='character',
            name='clothing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='characters.Clothing'),
        ),
        migrations.AddField(
            model_name='character',
            name='gear',
            field=models.ManyToManyField(blank=True, through='characters.CharacterGear', to='characters.Gear'),
        ),
        migrations.AddField(
            model_name='character',
            name='race',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='characters.Race'),
        ),
        migrations.AddField(
            model_name='character',
            name='weapons',
            field=models.ManyToManyField(blank=True, to='characters.Weapon'),
        ),
    ]
