# Generated by Django 3.0.5 on 2020-04-22 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('slug', models.SlugField(max_length=20)),
                ('description', models.TextField(blank=True)),
                ('skill_bonus', models.IntegerField(default=0)),
                ('str_bonus', models.IntegerField(default=0)),
                ('dex_bonus', models.IntegerField(default=0)),
                ('mind_bonus', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='class',
            options={'ordering': ['name'], 'verbose_name_plural': 'Classes'},
        ),
    ]
