# Generated by Django 3.0.5 on 2020-04-26 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='gear',
            field=models.ManyToManyField(blank=True, related_name='characters', through='characters.CharacterGear', to='characters.Gear'),
        ),
    ]
