# Generated by Django 3.0.5 on 2020-04-22 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0002_auto_20200422_2205'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField()),
                ('type', models.CharField(choices=[('L', 'Light'), ('M', 'Medium'), ('H', 'Heavy')], max_length=10)),
                ('cost', models.CharField(blank=True, max_length=10)),
                ('damage', models.CharField(blank=True, max_length=10)),
                ('range', models.CharField(blank=True, default='-', max_length=10)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='race',
            name='dex_bonus',
            field=models.IntegerField(default=0, verbose_name='DEX Bonus'),
        ),
        migrations.AlterField(
            model_name='race',
            name='mind_bonus',
            field=models.IntegerField(default=0, verbose_name='MIND Bonus'),
        ),
        migrations.AlterField(
            model_name='race',
            name='skill_bonus',
            field=models.IntegerField(default=0, verbose_name='Skill Bonus'),
        ),
        migrations.AlterField(
            model_name='race',
            name='str_bonus',
            field=models.IntegerField(default=0, verbose_name='STR Bonus'),
        ),
    ]
