# Generated by Django 3.0.5 on 2020-04-27 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0002_auto_20200426_2355'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='charactergear',
            options={'verbose_name': 'Adventuring Gear', 'verbose_name_plural': 'Adventuring Gear'},
        ),
        migrations.RemoveField(
            model_name='character',
            name='armor_class',
        ),
        migrations.AlterField(
            model_name='character',
            name='gear',
            field=models.ManyToManyField(blank=True, through='characters.CharacterGear', to='characters.Gear'),
        ),
    ]
