# Generated by Django 3.0.5 on 2020-04-22 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0003_auto_20200422_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weapon',
            name='cost',
            field=models.CharField(default='-', max_length=10),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='damage',
            field=models.CharField(default='-', max_length=10),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='range',
            field=models.CharField(default='-', max_length=10),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='type',
            field=models.CharField(choices=[('L', 'Light'), ('1H', 'One-Handed'), ('2H', 'Two-Handed'), ('R', 'Ranged')], max_length=10),
        ),
    ]
