# Generated by Django 3.0.5 on 2020-04-22 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0004_auto_20200422_2259'),
    ]

    operations = [
        migrations.CreateModel(
            name='Armor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField()),
                ('type', models.CharField(choices=[('L', 'Light'), ('M', 'Medium'), ('H', 'Heavy')], max_length=10)),
                ('cost', models.CharField(default='-', max_length=10)),
                ('ac_bonus', models.IntegerField(default=1, verbose_name='AC Bonus')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
