# Generated by Django 3.0.5 on 2020-04-23 03:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0005_armor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField()),
                ('cost', models.CharField(default='-', max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Gear',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='armor',
            options={'ordering': ['name'], 'verbose_name_plural': 'Armor'},
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100)),
                ('level', models.IntegerField(default=1)),
                ('xp', models.IntegerField(default=0)),
                ('str', models.IntegerField(default=10, verbose_name='STR')),
                ('dex', models.IntegerField(default=10, verbose_name='DEX')),
                ('mind', models.IntegerField(default=10, verbose_name='MIND')),
                ('phys', models.IntegerField(default=0, verbose_name='phys')),
                ('sub', models.IntegerField(default=0, verbose_name='sub')),
                ('know', models.IntegerField(default=0, verbose_name='know')),
                ('com', models.IntegerField(default=0, verbose_name='com')),
                ('melee_bonus', models.IntegerField(default=0, verbose_name='Melee Attack Bonus')),
                ('ranged_bonus', models.IntegerField(default=0, verbose_name='Ranged Attack Bonus')),
                ('magic_bonus', models.IntegerField(default=0, verbose_name='Magic Attack Bonus')),
                ('armor_class', models.IntegerField(default=10)),
                ('armor', models.ManyToManyField(blank=True, to='characters.Armor')),
                ('character_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='characters.Class')),
                ('gear', models.ManyToManyField(blank=True, to='characters.Gear')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='characters.Race')),
                ('weapons', models.ManyToManyField(blank=True, to='characters.Weapon')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
