# Generated by Django 3.2.7 on 2021-09-18 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0006_character_player'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='charactergear',
            options={'ordering': ['gear__name'], 'verbose_name': 'Inventory Item', 'verbose_name_plural': 'Inventory Items'},
        ),
        migrations.RemoveField(
            model_name='character',
            name='hit_points_max',
        ),
        migrations.AlterField(
            model_name='character',
            name='hit_points',
            field=models.IntegerField(default=1, verbose_name='Hit Points'),
        ),
    ]
