# Generated by Django 3.0.5 on 2020-04-23 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0006_auto_20200423_0314'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='copper',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='gold',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='hit_points',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='character',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='character',
            name='platinum',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='silver',
            field=models.IntegerField(default=0),
        ),
    ]
