# Generated by Django 3.0.5 on 2020-04-23 18:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0008_auto_20200423_0341'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weapon',
            options={'ordering': ['type', 'name']},
        ),
        migrations.RemoveField(
            model_name='armor',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='class',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='gear',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='race',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='weapon',
            name='slug',
        ),
        migrations.AlterField(
            model_name='character',
            name='com',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='character',
            name='know',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='character',
            name='magic_bonus',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='character',
            name='melee_bonus',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='character',
            name='ranged_bonus',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='character',
            name='slug',
            field=models.SlugField(default=uuid.uuid4),
        ),
        migrations.AlterField(
            model_name='character',
            name='sub',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='character',
            name='xp',
            field=models.IntegerField(default=0, verbose_name='XP'),
        ),
    ]
