# Generated by Django 3.2.7 on 2021-09-19 04:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0008_auto_20210918_0500'),
    ]

    operations = [
        migrations.CreateModel(
            name='GearInPack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('gear', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characters.gear', verbose_name='Item')),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Items',
                'ordering': ['gear__name'],
            },
        ),
        migrations.CreateModel(
            name='GearPack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('cost', models.CharField(default='-', max_length=10)),
                ('gear', models.ManyToManyField(blank=True, through='characters.GearInPack', to='characters.Gear')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='gearinpack',
            name='gearpack',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characters.gearpack'),
        ),
    ]
