# Generated by Django 3.0.5 on 2020-04-23 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0010_clothing'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='clothing',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='characters.Clothing'),
            preserve_default=False,
        ),
    ]
