# Generated by Django 3.0.5 on 2020-04-23 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0012_auto_20200423_2105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='race',
            name='skill_bonus',
        ),
        migrations.AddField(
            model_name='class',
            name='com_bonus',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='class',
            name='know_bonus',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='class',
            name='phys_bonus',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='class',
            name='special_ability',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AddField(
            model_name='class',
            name='sub_bonus',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='race',
            name='special_ability',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
    ]
