# Generated by Django 3.0.5 on 2020-04-23 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0015_auto_20200423_2147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='race',
            name='description',
        ),
    ]
