# Generated by Django 3.0.5 on 2020-04-23 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0016_remove_race_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='class',
            old_name='description',
            new_name='abilities',
        ),
    ]
