# Generated by Django 3.0.5 on 2020-04-23 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0017_auto_20200423_2152'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='abilities',
            field=models.TextField(blank=True),
        ),
    ]
