# Generated by Django 3.0.5 on 2020-04-26 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0018_race_abilities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='clothing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='characters.Clothing'),
        ),
    ]
