# Generated by Django 3.0.5 on 2020-04-26 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0019_auto_20200426_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='hit_points_max',
            field=models.IntegerField(default=1),
        ),
    ]
