# Generated by Django 3.0.5 on 2020-04-26 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0020_character_hit_points_max'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='magic_bonus',
        ),
        migrations.RemoveField(
            model_name='character',
            name='melee_bonus',
        ),
        migrations.RemoveField(
            model_name='character',
            name='ranged_bonus',
        ),
        migrations.AlterField(
            model_name='character',
            name='hit_points_max',
            field=models.IntegerField(default=1, verbose_name='Max HP'),
        ),
    ]
