# Generated by Django 3.0.5 on 2020-04-26 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0021_auto_20200426_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='weapons',
            field=models.ManyToManyField(blank=True, related_name='weapon', to='characters.Weapon'),
        ),
    ]
