# Generated by Django 3.0.5 on 2020-04-26 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0022_auto_20200426_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='weapons',
            field=models.ManyToManyField(blank=True, to='characters.Weapon'),
        ),
    ]
