# Generated by Django 3.0.5 on 2020-04-26 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0023_auto_20200426_2144'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='armor',
            options={'ordering': ['name'], 'verbose_name_plural': 'Armor'},
        ),
        migrations.AlterModelOptions(
            name='weapon',
            options={'ordering': ['name']},
        ),
    ]
